### ISSUE TITLE
Homepage hero-section video doesn't play by default

### ISSUE THREAD

**Issue by jeremy0x** [VictorJoey/Sesshin#8]
**Description**

The video on the hero section of the homepage isn't playing, and I think it should be playing by default.

**Comment by VictorJoey** [comment]
added `autoplay` attr?

**Comment by jeremy0x** [comment]
yeah.
```html
<video autoplay  loop id="hero-video" class="hero-video desktop-video">
  <source src="../media/pages/home/sesshin-trim_cropped.mp4" type="video/mp4" id="video-source">

  Your browser does not support HTML5 video.
</video>
```

**Comment by jeremy0x** [comment]
I just noticed it plays in other browsers, except Firefox (tested Chrome, Brave and Opera Browsers).

**Comment by VictorJoey** [comment]
> I just noticed it plays Brave Browser and Chrome, but not in Firefox and Opera Browsers.

Checking this
