### ISSUE TITLE
Homepage link redirects issue

### ISSUE THREAD

**Issue by jeremy0x** [VictorJoey/Sesshin#9]
**Description**

Clicking on any links on the homepage doesn't redirect to the right page, it simply reloads the page.

**Comment by VictorJoey** [comment]
target is set to parents by default. disable this from the javascript or simply add `target="_blank"` to the `a` tag

**Comment by jeremy0x** [comment]
I thought that was the normal/expected behavior. The implication of this is that new tabs will be opened anytime a link on the homepage is clicked.

**Comment by jeremy0x** [comment]
I thought that was the normal/expected behavior. The implication of this is that new tabs will be opened anytime a link on the homepage is clicked; and I don't think we'll want that.

**Comment by VictorJoey** [comment]
then let disable the page transition effect then.

**Comment by jeremy0x** [comment]
okay.

It should probably be added before the `Enter Site`.

**Comment by VictorJoey** [comment]
oh ... yea if the transition script is disabled, it disables both the intro animation as well. that's also not what we want.  give me some time to look into the script.
